-- Initial Catalog
INSERT INTO DISH_CATALOG ( NAME, "TYPE") VALUES ('Ensalada Tropical','FIRST');
INSERT INTO DISH_CATALOG ( NAME, "TYPE") VALUES ('Gazpacho','FIRST');
INSERT INTO DISH_CATALOG ( NAME, "TYPE") VALUES ('Entremeses','FIRST');

INSERT INTO DISH_CATALOG ( NAME, "TYPE") VALUES ('Filete','SECOND');
INSERT INTO DISH_CATALOG ( NAME, "TYPE") VALUES ('Emperador','SECOND');
INSERT INTO DISH_CATALOG ( NAME, "TYPE") VALUES ('Hamburguesa','SECOND');

INSERT INTO DISH_CATALOG ( NAME, "TYPE") VALUES ('Piña','DESSERT');
INSERT INTO DISH_CATALOG ( NAME, "TYPE") VALUES ('Tarta Queso','DESSERT');
INSERT INTO DISH_CATALOG ( NAME, "TYPE") VALUES ('Tarta Chocolate','DESSERT');


-- Example VALUES FOR LOCAL testing.
INSERT INTO USERS (NAME ) VALUES ('Pepe');
INSERT INTO USERS (NAME ) VALUES ('Juan');
